; config.ini
[common]
; 语言：Auto / zh_CN / en_US
Language=Auto

; 主窗口标题
WindowTitle=QtScrcpy-nadir

; 启动控制台输出文案，留空表示不输出。使用 \n 表示换行
StartupConsoleText=

; 推送到手机的默认路径（建议以 / 结尾）
PushFilePath=/sdcard/

; scrcpy-server 在手机端路径
ServerPath=/data/local/tmp/scrcpy-server.jar

; 视频渲染：-1 自动，0 软件，1 OpenGLES，2 DesktopOpenGL
UseDesktopOpenGL=-1

; 是否渲染过期帧（0/1）
RenderExpiredFrames=0

; 自定义 adb 路径（留空走默认）
AdbPath=

; 日志级别：verbose / debug / info / warn / error
LogLevel=info

; 编码器扩展参数（留空默认）
CodecOptions=

; 是否启用视频流（true/false）。false 等效 no-video 纯控模式。
VideoEnabled=true

; 无脚本远端光标总开关（true/false）
RemoteCursorEnabled=true

; 远端光标大小（像素，8~128）
CursorSizePx=64
